# Travis Continuous Integration script for travis-ci.org

language: java

jdk:
  - oraclejdk8
  - oraclejdk7

before_script:
  - sudo apt-get update
  - sudo apt-get install bash

script:
  - bash testall

